language: php

php:
    - '7.1'
    - '7.2'

env:
    global:
        - PHPUNIT_FLAGS='--stop-on-failure --verbose'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - make test
    - make coverage

after_script:
    - wget https://github.com/satooshi/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - php php-coveralls.phar --verbose
